Fix auth token request options in delete-unused-accounts-cron
1) Fix a typo in the option name: header -> headers

This was causing the request for the service-account access token to
fail with error:

   StatusCodeError: 403 - "Missing required header: Metadata-Flavor\n"

2) Specify json: true in the request options

Without this option, the response was returned as a string and not
parsed as json. Consequently, resp.access_token was undefined.