Add missing `firebase-database` script that was causing `public/index.js` to error out and add description for running and deploying sample client code to Firebase Hosting and Firebase Functions.
```js
TypeError: firebase.database is not a function. (In 'firebase.database()', 'firebase.database' is undefined) (index.js, line 155)
```